### ISSUE TITLE
Batch Size?

### ISSUE THREAD

**Issue by ftaker887** [omerbt/Splice#128]
Hello, very cool project! Is there a parameter to change the batch size? It seems that 8GB of VRAM isn't enough and I'm getting CUDA OOM errors. I've tried lowering the image resolutions but I still get the same issue.

**Comment by omerbt** [comment]
Thanks! for lower memory use we'd recommend using more lightweight ViT architectures, which can be configured by the `dino_model`  flag in https://github.com/omerbt/Splice/blob/b09099d6f943c631a43b8ce14a5239ec2fc1397a/conf/default/config.yaml#L27, e.g. `dino_vits16`. Note that the results shown in the paper were produced with `dino_vitb8`, so running with a different one might end up in different results.

**Comment by tnarek** [comment]
Hi, if you're facing memory issues, you can try running Splice in our [Colab notebook](https://colab.research.google.com/github/omerbt/Splice/blob/master/Splice.ipynb).
