### ISSUE TITLE
Disabling L_struct

### ISSUE THREAD

**Issue by urimerhav** [omerbt/Splice#131]
I'm trying to recreate the results in figure 9 in your paper. Specifically, disabling L_structure. Are both `lambda_global_ssim` and `lambda_entire_ssim` taken together form the entirety of L_struct or am I misreading the code? 

So far tinkering with the various lambda terms, it seems the result always retains very high structural fidelity to the structure image.

**Comment by tnarek** [comment]
Hi,
Our code technically allows the flexibility in the lambda terms for the global / entire branch (for L_structure and L_appearance). In our experiments we set them to be equal. So for ablation, we set `lambda_global_ssim = lambda_entire_ssim = 0`.
In some pairs the fidelity to the structure may be good even without it, but in many others it is crucial for maintaining structure (e.g., as in Fig. 9, in AFHQ, etc.)

**Comment by urimerhav** [comment]
Thanks for the clarification!
