### ISSUE TITLE
Codes of Inversion.

### ISSUE THREAD

**Issue by wzmsltw** [omerbt/Splice#132]
Dear authors:

Thanks for sharing your interesting work! Can you share the codes of inversion? Thanks!

**Comment by omerbt** [comment]
Thanks for reaching out, we consider creating a notebook of ViT features visualization which will probably include the [CLS] inversion code we used. We'll update you if we upload, closing the issue for now

**Comment by TheSouthFrog** [comment]
Also interested in the inversion code!

**Comment by pabloppp** [comment]
+1 to this request 🙇

**Comment by jjparkcv** [comment]
Still waiting for the request!

**Comment by tnarek** [comment]
Hi, we just published the code for feature inversion and self-similarity visualization :)

**Comment by tnarek** [comment]
Hi, we just published the code for [feature inversion](https://github.com/omerbt/Splice/blob/master/inversion.py) and [self-similarity visualization](https://github.com/omerbt/Splice/blob/master/keys_self_sim_pca.py) :)
