### ISSUE TITLE
How can I run your code using a GPU (3070) that has only 8G RAM?I got this error"RuntimeError: CUDA out of memory"

### ISSUE THREAD

**Issue by MaryFeng824** [omerbt/Splice#136]
Hi，
Could you please guide how to modify your code such that I could run it using a GPU with 8GB RAM?
![image](https://user-images.githubusercontent.com/39829876/152728217-59f1ade3-10c5-4cd4-b346-6a630f18fda7.png)

**Comment by omerbt** [comment]
Hi, for more memory efficient experiments you can try the following:
* work on lower resolution input images (which can be controlled by the parameters` A_resize`, `B_resize` in the config file.
* another alternative (less recommended in terms of quality of results) is to change the ViT architecture: change `model_name` to use a larger patch size (16) or the smaller model (vits). https://github.com/omerbt/Splice/blob/170928302c346d746c508ac970d19835fceaaa50/conf/default/config.yaml#L27 

Note that we also released a colab notebook, and you may get access to larger GPUs there.
